In [1]:
import pandas as pd

In [2]:
df = df = pd.read_csv('../../Data/automobileEDA.csv')
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          201 non-null    int64  
 1   normalized-losses  201 non-null    int64  
 2   make               201 non-null    object 
 3   aspiration         201 non-null    object 
 4   num-of-doors       201 non-null    object 
 5   body-style         201 non-null    object 
 6   drive-wheels       201 non-null    object 
 7   engine-location    201 non-null    object 
 8   wheel-base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb-weight        201 non-null    int64  
 13  engine-type        201 non-null    object 
 14  num-of-cylinders   201 non-null    object 
 15  engine-size        201 non-null    int64  
 16  fuel-system        201 non

In [13]:
to_select= ('engine-size', 'horsepower', 'highway-mpg', 'curb-weight')
to_select

('engine-size', 'horsepower', 'highway-mpg', 'curb-weight')

In [46]:
x = df.drop("price", axis=1)  
y = df['price']

In [53]:
X_train

array([[  97.        , 2302.        ,  120.        ,   34.        ],
       [  60.        , 1837.        ,   79.        ,   42.        ],
       [ 121.        , 2765.        ,  164.        ,   28.        ],
       [  76.        , 2024.        ,   92.        ,   34.        ],
       [  68.        , 2191.        ,   98.        ,   38.        ],
       [  78.        , 2337.        ,  111.        ,   29.        ],
       [ 114.        , 2912.        ,  141.        ,   28.        ],
       [  69.        , 2024.        ,   97.        ,   37.        ],
       [  73.        , 2240.        ,  108.        ,   31.        ],
       [  68.        , 1950.        ,   91.        ,   38.        ],
       [ 104.25615764, 2460.        ,  132.        ,   31.        ],
       [ 112.        , 2300.        ,   98.        ,   29.        ],
       [ 100.        , 2293.        ,  110.        ,   31.        ],
       [  68.        , 1989.        ,   90.        ,   38.        ],
       [  95.        , 3252.      

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=42)

array([[  97.        , 2302.        ,  120.        ,   34.        ],
       [  60.        , 1837.        ,   79.        ,   42.        ],
       [ 121.        , 2765.        ,  164.        ,   28.        ],
       [  76.        , 2024.        ,   92.        ,   34.        ],
       [  68.        , 2191.        ,   98.        ,   38.        ],
       [  78.        , 2337.        ,  111.        ,   29.        ],
       [ 114.        , 2912.        ,  141.        ,   28.        ],
       [  69.        , 2024.        ,   97.        ,   37.        ],
       [  73.        , 2240.        ,  108.        ,   31.        ],
       [  68.        , 1950.        ,   91.        ,   38.        ],
       [ 104.25615764, 2460.        ,  132.        ,   31.        ],
       [ 112.        , 2300.        ,   98.        ,   29.        ],
       [ 100.        , 2293.        ,  110.        ,   31.        ],
       [  68.        , 1989.        ,   90.        ,   38.        ],
       [  95.        , 3252.      

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()


In [49]:
X_train = X_train[to_select].values
X_test = X_test[to_select].values


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [45]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'nissan'

In [29]:
from sklearn.model_selection import cross_val_score as cvs
cvs(model, X_train, y_train, scoring='neg_mean_squared_error', cv=10)

array([ -3941156.92167898,  -9395752.40549005,  -4841653.22268162,
       -18976273.32055171,  -7026728.59139706,  -7926140.35506387,
       -11456040.66244923, -10268814.6791248 ,  -3475833.51482623,
       -25956453.16315525])