<h1>Numpy Notebook</h1>

In [1]:
import numpy as np

<h2>Array Creation</h2>

In [7]:
list1 = np.random.randint(9, size=(5))
list1

array([4, 3, 2, 1, 2])

In [8]:
type(list1)

numpy.ndarray

In [10]:
list2 = np.random.randint(20, size=(2, 4))
list2

array([[18,  2,  7, 10],
       [15, 13,  7,  6]])

In [12]:
arr2 = np.array(list2, dtype='float32')
arr2

array([[18.,  2.,  7., 10.],
       [15., 13.,  7.,  6.]], dtype=float32)

In [13]:
type(arr2)

numpy.ndarray

In [15]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((2,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones((2, 4), dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.full((2, 4), 4.5)

array([[4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5]])

In [27]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.random.random((3,3))

array([[0.68504211, 0.8477703 , 0.35490937],
       [0.58481791, 0.84868917, 0.62830295],
       [0.31007077, 0.15239095, 0.72128333]])

In [29]:
np.random.normal(0,1, (3,3))

array([[-0.67244493,  0.16425128, -0.92153258],
       [-0.74184649, -0.05732479,  0.31066712],
       [ 0.8930451 ,  0.18191424, -1.8663242 ]])

In [33]:
#

In [32]:
np.random.normal(0,2, (3,3))

array([[ 1.16189752,  4.26405241,  3.17549264],
       [ 1.91927378, -2.22246013, -0.51123204],
       [-0.97618943,  2.81167753,  1.94287149]])

In [36]:
sample_array = np.random.randint(10, size=(3,3))
np.array(sample_array, dtype='int')

array([[9, 5, 0],
       [0, 0, 3],
       [6, 0, 1]])

In [37]:
np.ndim(sample_array)

2

In [38]:
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
arr = np.array(nested_list)

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [39]:
np.ndim(arr)

3

In [41]:
arr.shape

(2, 3, 4)

In [42]:
arr.size

24

In [43]:
arr.dtype

dtype('int64')

In [44]:
arr.itemsize

8

<h2>Array Indexing</h2>

In [45]:
data=['hello', 'chetan', 20, 22]
print(data)

['hello', 'chetan', 20, 22]
