In [2]:
import numpy as np
arr=np.array([2,6,7,8,2,4])
arr

array([2, 6, 7, 8, 2, 4])

In [5]:
arr=np.array([2,6,7,8,2,4, 'hello'])
arr

array(['2', '6', '7', '8', '2', '4', 'hello'], dtype='<U21')

In [8]:
arr=np.array([2,6,7,8,2,4, 'hello'], dtype='object')
arr

array([2, 6, 7, 8, 2, 4, 'hello'], dtype=object)

<h1>Array Indexing</h1>

In [10]:
arr = np.array([0,1,2,3,4])


In [11]:
print(f"1st item: {arr[0]}")
print(f"2nd item: {arr[1]}")
print(f"3rd item: {arr[2]}")
print(f"4th item: {arr[3]}")

1st item: 0
2nd item: 1
3rd item: 2
4th item: 3


In [16]:
arr = np.random.randint(20, size=(3,3))
arr


array([[16, 19, 10],
       [ 4,  3,  8],
       [ 5,  5,  9]])

In [17]:
print(arr[0][2])

10


In [24]:
arr = np.array([0,1,2,3,4,6,7,8,9,33])

In [21]:
arr_slice=arr[1:3]
arr_slice

array([1, 2])

In [25]:
arr[4:]

array([ 4,  6,  7,  8,  9, 33])

In [26]:
arr[::2]

array([0, 2, 4, 7, 9])

In [27]:
arr[-3:-1]

array([8, 9])

In [28]:
arr[::-1]

array([33,  9,  8,  7,  6,  4,  3,  2,  1,  0])

In [29]:
arr = np.random.randint(33, size=(3,3))
arr

array([[28, 24,  7],
       [14,  8, 12],
       [ 8, 11, 16]])

<h1>Array Copy and View</h1>

In [30]:
base_array = np.array([1,4,5,6,7,8,7,8,9])
base_array

array([1, 4, 5, 6, 7, 8, 7, 8, 9])

In [36]:
copr_arr = np.copy(base_array)
copr_arr

array([1, 4, 5, 6, 7, 8, 7, 8, 9])

In [37]:
np.shares_memory(base_array, copr_arr)

False