### NumPy
- Stands for Numerical Python.
- NumPy is a python library used for working with arrays.
- NumPy array is a collection of homogeneous data types stored in contiguous memory location
- Has function for working in domain of linear algebra, fourier transform, and matrices.
- Written partially in Python, but parts that require fast computation are written in C or C++.
- Source code of NumPy is located at github repository.
    - https://github.com/numpy/numpy


### Why Numpy is Fast?  
- An array is a collection of homogeneous data types that are stored in contiguous memory locations.
- Vectorized operations are possible in NumPy.
- NumPy package integrates C, C++, and Fortran codes in Python.
    - These programming language have very little execution time compared to Python.


In [1]:
# need to import 3rd python packages
import numpy as np

### 1. Array Creation  
- create numpy array via 1D list
- create numpy array via 2D list
- create numpy array via built-in array creation functions.

| Data type | Description |
| --- | --- |
| bool_ | It represents the boolean value indicating True or False. It is stored as a byte |
| int_ | Default integer type (same as C long; normally either int64 or int32) |
| intc | Identical to C int (normally int32 or int64) |
| intp | Integer used for indexing (normally either int32 or int64) |
| int8 | It is the 8-bit integer identical to byte. (range: -128 to 127) |
| int16 | It is the 2byte 16 bit Integer (range: -32768 to 32767) |
| int32 | 4 byte, (32 bit) Integer (-2147483648 to 2147483647) |
| int64 | 8 byte, (64 bit) Integer (-9223372036854775808 to 9223372036854775807) |
| uint8 | 1 byte (8 bit) Unsigned integer (0 to 255) |
| uint16 | 2 byte (16 bit) Unsigned integer (0 to 65535) |
| uint32 | 4 byte (32 bit) Unsigned integer (0 to 4294967295) |
| uint64 | 8 byte (64-bit) Unsigned integer (0 to 18446744073709551615) |
| float_ | Shorthand for float64. |
| float16 | Half precision float: 5 bits are reserved for the exponent. 10 bits are reserved for mantissa, and 1 bit for sign |
| float32 | Single precision float: 8 bits are reserved for the exponent. 23 bits are reserved for mantissa, and 1 bit for sign |
| float64 | Double precision float: 11 bits are reserved for the exponent, 52 bits are reserved for mantissa, 1 bit for sign |
| complex_ | Shorthand for complex128. |


<b>NumPy Data Types</b>


- **create numpy array via 1D list**

In [2]:
# use .array() function

list1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5 6]


<details><summary>Click here for the solution</summary>

```python
list1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(list1)
print(arr1)
```
</details>

- **create numpy array via 2D list**
    - set explicitly data type to float32

In [3]:
# use .array(list ,dtype='float32')
list2 = [
    [1, 2, 3],
    [4, 5, 6]
]

arr2 = np.array(list2, dtype='float32')
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

<details><summary>Click here for the solution</summary>

```python
list2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(list2, dtype='float32')
print(arr2)
```
</details>

**create numpy array via built-in array creation functions**

In [6]:
# Q. create a length 10 integer array filled with zeros.
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<details><summary>Click here for the solution</summary>

```python
np.zeros(10, dtype='int')
```
</details>



In [7]:
# Q. create a 3x5 floating point array filled with ones
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<details><summary>Click here for the solution</summary>

```python
np.ones((3, 5), dtype='float')
```
</details>


In [8]:
# Q. create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

<details><summary>Click here for the solution</summary>

```python
np.full((3, 5), 3.14)
```
</details>

In [9]:
# Q. create an array filled with number in between 0 to 20, with step size 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

<details><summary>Click here for the solution</summary>

```python
np.arange(0, 20, 2)
```
</details>

In [11]:
# Q. create 3x3 array from uniform distribution between 0 and 1

np.random.random((3, 3))

array([[0.56723407, 0.13122282, 0.2089109 ],
       [0.66959534, 0.98199365, 0.54452705],
       [0.01138079, 0.43453515, 0.11057522]])

<details><summary>Click here for the solution</summary>

```python
np.random.random((3, 3))
```
</details>

In [12]:
# Q. create 3x3 array from normal distribution with mean = 0 and standard deviation = 1

np.random.normal(0, 1, (3, 3))


array([[ 0.90260492,  0.3931753 ,  1.62831253],
       [ 0.40040562, -0.35236601, -0.16139667],
       [ 1.55566909,  2.34284971, -0.04619446]])

<details><summary>Click here for the solution</summary>

```python
np.random.normal(0, 1, (3, 3))
```
</details>

In [13]:
# Q. Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 4, 7],
       [6, 4, 4],
       [9, 1, 5]])

<details><summary>Click here for the solution</summary>

```python
np.random.randint(0, 10, (3, 3))
```
</details>

### 2. Attributes of NumPy Array  
- **ndarray.ndim:** _Represents the number of dimensions(axes) of the ndarray_
- **ndarray.shape:** _Gives the tuple of integers representing the size of the ndarray in each dimension_
- **ndarray.size:** _Gives the total number of elements in the ndarray. Equals to the product of elements of the result of the attribute **shape**_
- **ndarray.dtype:** _tells the data type of the elements of a Numpy array. In Numpy array, all the elements have the same data type._
- **ndarray.itemsize:** _returns the size(in bytes) of each element of a Numpy array._




In [2]:
# create 2D numpy array
import numpy as np
sample_array = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

In [3]:
# ndarray.ndim
print(f"The dimension of sample array is: {sample_array.ndim}")

The dimension of sample array is: 3


<details><summary>Click here for the solution</summary>

```python
print(f"The dimension of sample array is: {sample_array.ndim}")
```
</details>

In [4]:
# ndarray.shape

print(f"The shape of sample array is: {sample_array.shape}")

The shape of sample array is: (1, 3, 3)


<details><summary>Click here for the solution</summary>

```python
print(f"The shape of sample array is: {sample_array.shape}")
```
</details>

In [5]:
# ndarray.size

print(f"The total number of elements in the sample array is: {sample_array.size}")

The total number of elements in the sample array is: 9


<details><summary>Click here for the solution</summary>

```python
print(f"The total number of elements in the sample array is: {sample_array.size}")
```
</details>

In [6]:
# ndrray.dtype

print(f"The data type of elements of sample array is: {sample_array.dtype}")

The data type of elements of sample array is: int64


<details><summary>Click here for the solution</summary>

```python
print(f"The data type of elements of sample array is: {sample_array.dtype}")
```
</details>

In [7]:
# ndarray.itemsize, returns the size (in bytes) of each element of a Numpy array

print(f"The size of each element in the numpy array is: {sample_array.itemsize}")

The size of each element in the numpy array is: 8


<details><summary>Click here for the solution</summary>

```python
print(f"The size of each element in the numpy array is: {sample_array.itemsize}")
```
</details>

### 3. Array Indexing  
`3.1 Indexing 1D array`  
 <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneNp.png" width = "400">    

      source: https://cognitiveclass.ai/



In [10]:
# create 1D array from 1D list of (length = 5) and value in range [0, 4].
# access each array element via indexing
a = np.array([0, 1, 2, 3, 4])

print(f'1st item: {a[0]}')
print(f'2nd item: {a[1]}')
print(f'3rd item: {a[2]}')
print(f'4th item: {a[3]}')

1st item: 0
2nd item: 1
3rd item: 2
4th item: 3



`3.2 Indexing 2D array`  
<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png" width = "400">   

         source: https://cognitiveclass.ai/

In [11]:
# create 2D array from 2D list as in above figure.
# access each array element via @D array indexing
arr_idx_2d = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

print(arr_idx_2d[0,0])
print(arr_idx_2d[0,1])
print(arr_idx_2d[0,2])
print(arr_idx_2d[1,0])
print(arr_idx_2d[1,1])
print(arr_idx_2d[1,2])
print(arr_idx_2d[2,0])
print(arr_idx_2d[2,1])
print(arr_idx_2d[2,2])


11
12
13
21
22
23
31
32
33


### 4. Array Slicing: Accessing Subarrays
- Slicing means taking elements from one given index to another
- Syntax: array[start_index:end_index:step]
- conditions:
    - If we don’t pass start its considered as 0
    - If we don’t pass end its considered length of array in that dimension
    - If we don’t pass step its considered as 1
- case:
    - step is positive: left to right indexing
    - step is negative: right to left indexing

- `Note`: end index is exclusive



`4.1 Slicing 1D array`


example array: [1, 2, 3, 4, 5, 6, 7]


In [12]:
# create array
# slice array
#
# Q. Slice elements from index 1 to index 5 from the example array.

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[1:5]

print(arr1_slice)

[2 3 4 5]


<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[1:5]

print(arr1_slice)
```
</details>

In [13]:
# Q. slice elements from index 4 to  the end of the array
# hint: [4:]

arr1[4:]

array([5, 6, 7])

<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[4:]
print(arr1_slice)
```
</details>

In [14]:
# Q. return every element from numpy array  with step 2 i.e. elements at even index.
# hint: [::2]

arr1[::2]

array([1, 3, 5, 7])

<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[::2]
print(arr1_slice)
```
</details>

In [15]:
# Q. Slice from the index 3 from the end to index 1 from the end
# hint: [-3:-1]

arr1[-3:-1]

array([5, 6])

<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[-3:-1]
print(arr1_slice)
```
</details>

In [16]:
# Q. Reverse 1D array.
# hint: [::-1]

arr1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_rev = arr1[::-1]
print(arr1_rev)
```
</details>

`4.1 Slicing 2D array`


example array:

    [[11, 12, 13],  
    [21, 22, 23],  
    [31, 32, 33]]  

In [18]:
# create 2D array

arr2 = np.array([
    [11, 12, 13],
    [21, 22, 33],
    [31, 32, 33]
])

# slice number 22 and 23

arr2[1, 1:]

array([22, 33])

### 5. Copy and View [OPTIONAL]
- Copy means copy of an original array.
- view means just an view of an original array.
- When new array is created via copying array, newly created array doesn't shares the memory with original array.
- When new array is created via view of an array, newly created array shares the memory with original array.

In [19]:
# create sample array

base_arr= np.array([1, 2, 3, 4, 5, 6])
print(base_arr)

[1 2 3 4 5 6]


In [20]:
# 1. create copy of base array

copy_arr = base_arr.copy() # same memory location share or NOT
# copy_arr = base_arr # same memory location share or NOT
print(copy_arr)

[1 2 3 4 5 6]


<details><summary>Click here for the solution</summary>

```python
copy_arr = base_arr.copy()
print(copy_arr)
```
</details>

In [21]:
# test memory sharing between base and copy array
# hint: np.shares_memory(arr1, arr2)

print(f"""Do original array and copy array shares an memory?
      Ans: {np.shares_memory(base_arr, copy_arr)}""")

Do original array and copy array shares an memory?
Ans: False


<details><summary>Click here for the solution</summary>

```python
print(f"Do original array and copy aray shares an memory?\nAns: {np.shares_memory(base_arr, copy_arr)}")
```
</details>

In [22]:
# 2. create view of base array

view_arr = base_arr.view()
print(view_arr)

[1 2 3 4 5 6]


<details><summary>Click here for the solution</summary>

```python
view_arr = base_arr.view()
```
</details>

In [23]:
# test memory sharing between base and view array
# hint: np.shares_memory(arr1, arr2)

print(f"Do original array and view array shares an memory?\nAns: {np.shares_memory(base_arr, view_arr)}")

Do original array and view array shares an memory?
Ans: True


<details><summary>Click here for the solution</summary>

```python
print(f"Do original array and copy aray shares an memory?\nAns: {np.shares_memory(base_arr, view_arr)}")
```
</details>

**Note:**
- If view of an array shares the memory then the memory address of original array and view of an array should be equal.
- Let's now test the memory address.
- `id()` function gives the identity of the different python objects such as integer, string, etc but it doesn't mean that is the exacy memory address.

Let's define a python function to print memory address of original_array, copy_array, and view_array.

In [27]:
def get_memory_address(arr):
    return arr.__array_interface__["data"][0]

In [28]:
# memory address of base array
print(get_memory_address(base_arr))

48627104


In [29]:
# memory address of view array
print(get_memory_address(view_arr))

48627104


In [30]:
# memory address of copy array
print(get_memory_address(copy_arr))

48969664


- `memory address of base array and view array is same`
- `memory address of base array and copy array is different`

**updating content of view array changes original base array**

In [31]:
# update item at index=0 from view array
view_arr[0] = 100
print(view_arr)

[100   2   3   4   5   6]


In [32]:
# verify changes in base array
print(base_arr)

[100   2   3   4   5   6]


In [33]:
# but, copy array is unchanged
print(copy_arr)

[1 2 3 4 5 6]


- Thus,
  - updating content of view array, updates original array
  - updating content of copy array, doesn't changes the original array

### 6. Subarrays as no-copy view
- Subarrays created via slicing original arrays is the view of an original arrays.
- Changing content in the sliced array, changes the original array as well.

In [34]:
# create new 1D array of shape: (9, )
base_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 3])
print(base_arr)

[1 2 3 4 5 6 7 8 3]


In [36]:
# sliced first 3 items
sliced_arr = base_arr[:3]
print(sliced_arr)

[1 2 3]


In [37]:
# test memory address
print(get_memory_address(base_arr))
print(get_memory_address(sliced_arr))

48943456
48943456


- `Memory address of original array and sliced array is same.`
- `Updating sliced array content also updates the original array content and vice-versa.`


### 7. Reshaping of Arrays
- The shape of an array is number of element in each dimensions like (2, 3).
- Reshaping means changing the shape of an array.
- By reshaping we can add or remove dimensions or change the number of elements in each dimension.
- **Example:**
  - Resphape 1D to 2D
  - Reshape 1D to 3D



#### 7.1 Reshape 1D to 2D  
**`Q. Reshape following 1D array with 12 elements to 2D array of shape (4, 3)`**

  - arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])



In [4]:
# write your program here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
np.reshape(arr, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 7.2 Reshape 1D to 3D

**`Q. Reshape following 1D array with 12 elements to 3D array of shape (2, 3, 2)`**
- arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])



In [5]:
# write your program here
arr.reshape((2, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

#### 7.3 Can we reshape to any shape?
- Yes, as long as element required for reshaping are equal in both shapes.

**`Q. Convert 1D array with 8 elements to a 2D array with shape (3, 3)`**
- arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [6]:
# write your program here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape((3, 3))

ValueError: cannot reshape array of size 8 into shape (3,3)

- This process raise an exception, since there are 8 elements before reshaping and 9 elements after reshaping.
- For reshaping to happen, number of elements before reshaping should be equal to number of elements after reshaping.

### 8. Joining Arrays
- Array Joining means putting content of two or more array in a single array
- In SQL  we join tables based on keys, whereas in NumPy we join arrays by axes.
- Array Joining can be done in two ways:
  - `Concatenation:` using concatenate() function
  - `Stacking:` using stack() function



#### 8.1 Concatenation
- We pass  sequence of arrays that we want to the **concatenate()** function.
- After concatenating dimensions of resulting array will be same as that of individual array.
- Order of concatenation will be based on the order in which array are passed to the **concatenate()** function.

- **Syntax:**
  - `np.concatenate((a1, a2,....), axis=0, out=None)`
    - a1, a2, … :  Sequence of array_like. The array must  have the same shape
    - axis: Int, optional.  axis along which array will be concatenated
    - out: ndarray, optional.  The destination to place the result.

**Q. Concatenate 1D Array**

In [3]:
# write your program here
arr1 = np.array([1, 1, 1, 1])
arr2 = np.array([2, 2, 2, 2])

concat_arr = np.concatenate((arr1, arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

**Q. Concatenate 2D Array (axis = 0)**

In [4]:
# write your program here

a = np.array([
    [1, 1, 1],
    [1, 1, 1]
])

b = np.array([
    [9, 9, 9],
    [9, 9, 9]
])

concat_0 = np.concatenate((a, b))
concat_0

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

**Q. Concatenate 2D Array (axis = 1)**

In [5]:
# write your program here

concat_1 = np.concatenate((a, b), axis=1)
concat_1

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

### 9. Splitting Arrays
- Splitting is reverse operations of joining
- Joining merges multiple arrays into one.
- Splitting breaks one array into multiple one.
- Can be implemented using numpy functions:
  - `numpy.split()`
  - `numpy.array_split()`

- We pass array we want to split and the number of split.
- Sub-arrays obtained after splitting is only view of the original arrays.
  - Changes made to the sub-arrays also reflect changes in the original array.


**Splitting 1D array i.e. [1, 2, 3, 4, 5, 6] into 4 parts**

In [6]:
# initialize array
split_array = np.array([1, 2, 3, 4, 5, 6])
print(split_array)

[1 2 3 4 5 6]


In [18]:
# 1. using numpy.split()
# Hint: .split(array, 4)
np.split(split_array, 4)

ValueError: array split does not result in an equal division

In [19]:
# 2. using numpy.array_split()
# Hint: .array_split(array, 4)
np.array_split(split_array, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

**Splitting 2D array (axis = 0)**

In [3]:
# Define array
split_array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

In [15]:
# 1. using array_split for 3 split
# Hint: .array_split(array, 3)
np.array_split(split_array_2d, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [4]:
# 2. using split for 3 split
# Hint: .split(array, 3)

np.split(split_array_2d, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

**Splitting 2D array (axis = 1)**

In [5]:
# 1. using array_split
# Hint: .array_split(array, 3, axis=1)

np.array_split(split_array_2d, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [6]:
# 1. using split
# Hint: .split(array, 3, axis=1)

np.split(split_array_2d, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

### 9. Numpy Universal Functions (Ufuncs)
- Looping over the array to perform repeated task like addition, subtraction, etc on each array element are common.
- Computation time to perform such repeated task increases with relatively larger data.
- NumPy makes this faster by using vectorized operations, implemented through **ufuncs**
- **Types:**
  - `Unary Ufuncs`
    - Operates on single inputs.
    - Example: negation of input array x

  - `Binary Ufuncs`
    - Operates on two inputs.
    - Example: addition of two input array x and y



| Operator | Equivalent ufunc | Description |  
|----------|------------------|-------------|
| `+`      | `np.add`         | Element-wise addition (e..g 1+1 = 2) |
| `-`      | `np.subtract`    | Element-wise subtraction (e.g. 1-1 = 0) |
| `*`      | `np.multiply`    | Element-wise multiplication (e.g. 1*1 = 1) |
| `/`      | `np.divide`      | Element-wise division (e.g. 1/1 = 1) |
| `//`     | `np.floor_divide`| Element-wise floor division (e.g. 1//1 = 1)|
| `%`      | `np.mod`         | Element-wise modulo (e.g. 1%1 = 0)|
| `**`     | `np.power`       | Element-wise exponentiation (e.g. 1**1 = 1)|
| `abs()`  | `np.abs`         | Element-wise absolute value(e.g. np.abs(-1) = 1) |

#### 9.1 Computation Time (without Ufuncs)


In [2]:
import time 

# write your program here

x1 = np.arange(1, 10000000)
x2 = np.arange(1, 10000000)

# array to hold multiplications
mul = np.zeros(x1.shape)

start_time = time.process_time()

for i in range(len(x1)):
  mul[i] = x1[i] * x2[i]

end_time = time.process_time()

print(end_time - start_time)

7.268750715000001


#### 9.2 Computation Time (with Ufuncs)


In [3]:
# write your program here

start_time = time.process_time()

# mul_unfunc = np.multiply(x1, x2)
mul_unfunc = x1 * x2

end_time = time.process_time()

print(end_time - start_time)

0.20835461899999963


- **Note:**
  - Using Ufuncs, computation time is less compared to classic python for loops.
  - The reason behind less computation time using ufuncs is due to **Vectorization**

### 10. Vectorization

- It’s a technique in order to getting rid of  explicit for loop in python.
- Vectorization can be performed using parallelization instruction called
 **SIMD** instruction.
 - SIMD stands for single instruction multiple data.
 - In python SIMD is enabled through Ufuncs.
  - Helps python NumPy to take much better advantage of parallelism to do computation faster.


- **Deep Learning**
    - Famous in different task such as Classification, Segmentation, Detection, etc.
    - Deep Learning demands large number of data that helps model to generalize.
    - Large number of training set leads to large number of time to run the code i.e. need to wait long time to get the result.
    - So, in deep learning ability to perform vectorization has become key skill.

- **Note:**
  - whenever possible avoid using explicit for loops





### 11. Broadcasting in Python
- Broadcasting is a powerful feature in NumPy that allows for element-wise operations between arrays of different shapes and sizes.
- What will happen if we add 2 numpy array of different shapes?
  - This can be answered using the concepts of Broadcasting.


- **Working:**
  - NumPy performs broadcasting by automatically expanding dimensions of smaller arrays to match the shape of larger arrays.
  - Broadcasting follows a set of rules to determine how dimensions should be aligned for element-wise operations.

- **Broadcasting Rules:**
  - `Rule 1: `
    - If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

  - `Rule 2:`
    - If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

  - `Rule 3:`
    - If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

**1. Broadcasting with Scalars**

In [ ]:
# write your program here

a = np.array([1, 2, 3])
b = 2

print(a + b)

[3 4 5]


- `Explanation:`
  - shape of a: (3,)
  - shape of b: None

  - Rule1: Make shape of b to that of a
    - i.e. shape of b: (1,)

  - Rule2: Stretched b to make shape equal to a
    - i.e. shape of b: (3,)

  - Both a and b are of same shape Perform addition

**2. Broadcasting with 1D and 2D Arrays**

In [ ]:
# write your program here

a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

print(f"shape of a: {a.shape}")
print(f"shape of b: {b.shape}")

print(f"\na + b = {a + b}")

shape of a: (3,)
shape of b: (3, 1)

a + b = [[11 12 13]
 [21 22 23]
 [31 32 33]]


- `Explanation:`
  - a is 1 dimension less to that b.

  - Rule1: increase dimension of a by adding 1 in left side.
    - new shape of a: (1, 3)

  - Rule2:
    - stretch dimension 1 of a to match to dimension of b
      - shape: (3, 3)
    - stretch dimesion 1 of b to match to dimension of a
      - shape: (3, 3)

  - Perform addition, since shape of 2 arrays are same

**3. Broadcasting with Incompatible Shapes**

In [ ]:
# write your program here
a = np.array([1, 3])
b = np.array([1, 2, 3])

print(a + b)

ValueError: ignored

- `Explanation:`
  - Both array a and b are of same dimensions. So Rule 1 is not applicable.
  - Neither of array a and b have dimension 1 to stretch for making both array of same size. So, Rule 2 is not applicable.
  
  - Addition is not possible, since arrays are of different shape

### 12. Numpy Aggregations
- It is the process of summarizing large dataset into a smaller set of values that capture key characteristics of the data.
- Numpy consists of set of functions that allows user to perform aggregations operations on datasets.

| Function Name | NaN-safe Version | Description |
|---------------|------------------|-------------|
| np.prod       | np.nanprod       | Compute product of elements |
| np.mean       | np.nanmean       | Compute mean of elements |
| np.std        | np.nanstd        | Compute standard deviation |
| np.var        | np.nanvar        | Compute variance |
| np.min        | np.nanmin        | Find minimum value |
| np.max        | np.nanmax        | Find maximum value |
| np.argmin     | np.nanargmin     | Find index of minimum value |
| np.argmax     | np.nanargmax     | Find index of maximum value |
| np.median     | np.nanmedian     | Compute median of elements |
| np.percentile | np.nanpercentile | Compute rank-based statistics |
| np.any        | N/A              | Evaluate whether any elements are true |
| np.all        | N/A              | Evaluate whether all elements are true |



In [3]:
# Define sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# compute mean
# Hint: np.mean(arr)

np.mean(arr)

4.5

In [5]:
# compute standard deviation
# Hint: np.std(arr)

np.std(arr)

2.29128784747792

In [6]:
# compute variance
# Hint: np.var(arr)

np.var(arr)

5.25

In [7]:
# get min value
# Hint: np.min(arr)

np.min(arr)

1

In [8]:
# get max value
# Hint: np.max(arr)

np.max(arr)

8

In [9]:
# get index of min value
# Hint: np.argmin(arr)

np.argmin(arr)

0

In [10]:
# get index of max value
# Hint: np.argmax(arr)

np.argmax(arr)

7

In [11]:
# get 25% percentile
# Hint: np.percentile(arr, 25)


np.percentile(arr, 25)

2.75

In [12]:
# check if any value is less than 3
# Hint: np.any(arr<3)

np.any(arr<3)

True

In [13]:
# check if all values are less than 3
# Hint: np.all(arr<3)

np.all(arr<3)

False