In [10]:
import numpy as np
arr = np.random.randint(33, size=(4,4))
arr

array([[ 7, 18, 24, 13],
       [29,  9, 23, 18],
       [ 0, 11, 22, 19],
       [16,  8, 17, 18]])

In [15]:
newarr= np.array([1,1,1,1,1,1,1,1])
print(len(newarr))
np.reshape(newarr, (2,4))

8


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
arr1 = np.array([1,1,1,1])
arr2 = np.array([2,2,2,2])
concat = np.concatenate((arr1, arr2))
concat

array([1, 1, 1, 1, 2, 2, 2, 2])

In [22]:
a = np.array([[1,1,1],[2,2,2]])
b = np.array([[3,3,3],[4,4,4]])
conct = np.concatenate((a,b))
conct

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [24]:
new_concat = np.concatenate((a,b), axis=1)
new_concat

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

In [27]:
np.split(new_concat, 4)

ValueError: array split does not result in an equal division

In [28]:
np.array_split(new_concat, 4)

[array([[1, 1, 1, 3, 3, 3]]),
 array([[2, 2, 2, 4, 4, 4]]),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64)]

In [29]:
arr2d = np.random.randint(50, size=(4,4))
arr2d

array([[21, 16, 43, 38],
       [13, 41, 20, 48],
       [42, 10, 20, 35],
       [ 1, 39,  9, 44]])

In [30]:
np.array_split(arr2d, 4)

[array([[21, 16, 43, 38]]),
 array([[13, 41, 20, 48]]),
 array([[42, 10, 20, 35]]),
 array([[ 1, 39,  9, 44]])]

In [31]:
np.array_split(arr2d, 3)

[array([[21, 16, 43, 38],
        [13, 41, 20, 48]]),
 array([[42, 10, 20, 35]]),
 array([[ 1, 39,  9, 44]])]

In [33]:
np.split(arr2d, 4, axis=1)

[array([[21],
        [13],
        [42],
        [ 1]]),
 array([[16],
        [41],
        [10],
        [39]]),
 array([[43],
        [20],
        [20],
        [ 9]]),
 array([[38],
        [48],
        [35],
        [44]])]

In [35]:
import time
x1 = np.arange(1, 1000000)
x2 = np.arange(1, 1000000)

mul = np.zeros(x1.shape)
print(mul)
start_time= time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]

end_time = time.process_time()
print(end_time - start_time)

[0. 0. 0. ... 0. 0. 0.]
0.6111814330000005


In [36]:
a= np.array([1,2,3])
b = 2
print(a+b)

[3 4 5]


In [37]:
b = np.array([[10], [20], [30]])
print(a.shape)
print(b.shape)
print(a+b)

(3,)
(3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [38]:
a = np.array([1,3])
b = np.array([1,2,3])
a+b


ValueError: operands could not be broadcast together with shapes (2,) (3,) 