## Conditions and Branching.
- `if`, `elif`, `else` keywords are used to accomplish conditions and branching in python.

  ```
  if case1:
      perform action1
    
  elif case2:
      perform action2

  else:
      perform action3
  ```

- Different comparison operators shown below, can be used with if statements.
  - `Equals: a == b`
  - `Not Equals: a != b`
  - `Less than: a < b`
  - `Less than or equal to: a <= b`
  - `Greater than: a > b`
  - `Greater than or equal to: a >= b`

  ```
  if a > b:
      print("a is greater than b")

  elif a == b:
      print("a is equal to b")

  else:
      print("a is less than b")
  ```

- In this lecture we'll cover:
  - if statement: How program enters if block.
  - Simple if else statements.
  - Nested if else statements.
  - Short Hand if....else statements / Ternary Operators
  - pass keyword

##1. if statement: How python program enters if blocks?

`Hint: when if conditions is True`

```
if True:
  print("if block goes here")

if False:
;
  print("if block goes here")
```

In [1]:
# explain here

if True:
  print("if block goes here")


if False:
  print("If block goes here")

if block goes here


- Python relies on Indentation (whitespace at the beginning of a line)
  - Other programming languages often use curly-brackets for this purpose.

`Q.Try if statement without Indentation.`

In [2]:
# write your program here.
if True:
print("if block statement")

IndentationError: expected an indented block after 'if' statement on line 2 (833065042.py, line 3)

_`if statement, without indentation (will raise an error)`_





##2. Simple if else statements
- Generally, if statement has an optional elif, else clause.
- **syntax 1**

  ```
  if condition:
      # block of code if condition is True
  
  else:
      # block of code if condition is False
  ```

- **syntax 2**

  ```
  if condition1:
      # code block 1
  
  elif condition2:
      # code block 2

  else:
      # code block 3
  ```


 **Q1. Input number from user. print "postive number" if number is positive else print "negative number. Consider 0 as positive as well."**



In [5]:
 ## write your program here
def take_input(User_Data):
    
    if User_Data >= 0:
        print("Positive Number")
    else:
        print("negative Number")
User_Data = int(input("Give your Number: "))
take_input(User_Data)

Give your Number:  -7


negative Number


**Q2. Input two numbers num1, and num2 from user,**
  - _**if num1 > num2: print "num1 > num2"**_
  - _**if num1 == num2: print "num1 = num2"**_
  - _**if num1 < num2: print "num1 < num2"**_

In [6]:
## write your program here
def Compare_Num(num1, num2):
    
    if num1 > num2:
        print(" num1 > num2")
    elif num1 == num2:
        print ("num1 = num2")
    elif num1 < num2:
        print ("num1 < num2")
        
num1 = int(input("Give Number 1"))
num2 = int(input("Give Number 2"))

Compare_Num(num1, num2)

Give Number 1 7
Give Number 2 8


num1 < num2


##3. Nested if else statements.
- if or else statements inside if or else statements.

- **Syntax:**
  ```
  if condition1:
    if condition:
      # code block
    else:
      # code block

  elif condition2:
    if condition:
      # code block
    else:
      # code block
  
  :::::::::::::::::
  :::::::::::::::::

  else:
    if condition:
      # code block

    elif condition:
      # code block
    else:
      # code block
  ```

**Q. Write a python program to find max of three numbers.**

```
Given three numbers num1, num2, num3

if num1 > num2:
  if num1 > num3:
    print(f"max number: {num1}")
  else:
    print(f"max number: {num3}")


else:
  if num2 > num3:
    print(f"max number: {num2}")
  else:
    print(f"max number: {num3}")
```





In [11]:
## write your program here

def Calculate_Max(num1, num2, num3):

    if num1 > num2:
      if num1 > num3:
        print(f"\nMax number: {num1}")
      else:
        print(f"\nMax number: {num3}")

    else:
      if num2 > num3:
        print(f"\nMax number: {num2}")
      else:
        print(f"\Max number: {num3}")

num1 = int(input("Give Number 1"))
num2 = int(input("Give Number 2"))
num3 = int(input("Give Number 3"))

Calculate_Max(num1, num2, num3)

Give Number 1 6
Give Number 2 9
Give Number 3 3



Max number: 9


##4. Short Hand if...else statements / Ternary Operators
- It is way of writing if else statement in a single line of code.
- Also, called Ternary operators.
- **Syntax (simple if else)**

  `<if_block> if <condition>  else  <else_block> `


- **Syntax (nested simple if else)**

  `(<code_block> if <condition> else <code_block>)` **if**  < if_condition >
   **else** `(<code_block> if <condition> else <code_block>)`



   **Q1. Write a python program to print max of 2 numbers using ternary operator.**

      ```
      Input: a = 20, b = 30
      Output: Max number is 30
      ```


In [14]:
## write your Ternary program here
def Ternery_Use(num1):
    print("Positive") if num1 >= 0 else print("negative")

num1 = int(input("Give num to check ternery use case"))
Ternery_Use(num1)

Give num to check ternery use case -4


nehative


**Q2. Write a python program to print max of 3 numbers using ternary operator.**

In [20]:
num1 = 10
num2 = 20
num3 = 30

max = print(num1) if num1 > num2 and num > num3 else print(num2) if num2 > num3 else print(num3)

30


In [21]:
## write your program here
# max between three numbers

def Ternery_Use(num1, num2, num3):
    print(f"\nMax number: {num1}") if num1 > num2 and num1 > num3  else print(f"\nMax number: {num2}") if num2 > num3 else print(f"\Max number: {num3}")

num1 = int(input("Give Number 1"))
num2 = int(input("Give Number 2"))
num3 = int(input("Give Number 3"))

Ternery_Use(num1, num2, num3)


Give Number 1 5
Give Number 2 8
Give Number 3 3



Max number: 8


## 5. Pass Keyword
- `pass` keyword acts as a placeholder for code to be added in if..else block.

- **Use case**
  - consider case, when you want to determine your python code structure in advance before adding actual code.

- **Syntax:**

  ```
  if <condition>:
    pass
  else <condition>:
    pass
  ```

In [22]:
## write your program using "pass" keyword
if True:
  pass

else:
  pass

# Task 01: Grading System Exercise

## Objective
Create a simple grading system where a student's score is entered, and the program determines the corresponding grade.

## Requirements

1. Get the student's score as input.
2. Use the following grading scale:
   - 90-100: A
   - 80-89: B
   - 70-79: C
   - 60-69: D
   - Below 60: F
3. Print the grade based on the input score.
4. Handle cases where the entered score is not within the valid range (0-100).

In [26]:
def Grade_Calculate(marks):
    
    if marks>90 and marks <100:
        print("The grade is A")
    elif marks>80 and marks<89:
        print("The grade is B")
    elif marks>70 and marks<79:
        print("The grade is C")
    elif marks>60 and marks<69:
        print("The grade is C")
    elif marks>=0 and marks<60:
        print("The grade is F")
    else:
        print("Please Double check your marks")

marks = float(input("Give Number of Student: "))
Grade_Calculate(marks)

Give Number of Student:  67


The grade is C


# Task 02: Ticket Price Calculator Exercise

## Objective
Create a program that calculates the ticket price for a movie based on the age and whether the customer is a student.

## Requirements

1. Get the user's age and whether they are a student (True or False) as input.
2. Define the ticket prices:
   - Children (age 0-12): \$10
   - Teenagers (age 13-17): \$15
   - Adults (age 18 and above): $20
   - Students (regardless of age): \$18 (discounted price)
3. Calculate and print the ticket price based on the user's age and student status.
4. Handle cases where the entered age is not a valid numeric value.
5. Provide a message for cases where the age is negative or non-integer.

In [17]:
def Ticket_Price(student, age):
    
    if student == "y" and "Y":
        if age>=0 and age<12:
            print("Price is $10")
        elif age>13 and age<17:
            print("Price is $15")
        elif age>18:
            print("Price is $20")
        else:
            print("invalid age")
    elif student == "n" and "N":
        print("Unable to provide student discount")
    else:
        print("Invalid command")
        print("Unable to provide student discount")
        
def User_Input():

    student = str(input("Please type y if you are student, n if you are not student"))
    
    age = int(input("Please give age: "))

    Ticket_Price(student, age)

User_Input()

Please type y if you are student, n if you are not student uh
Please give age:  8


Invalid command
Unable to provide student discount


# Task 03: Word Frequency Counter

## Objective
Create a program that analyzes a given text and counts the frequency of each unique word.

## Requirements

1. Ask the user to input a paragraph or sentence.
2. Tokenize the input into words (ignoring punctuation and case sensitivity).
3. Count the frequency of each unique word.
4. Display the word frequencies in alphabetical order.
5. Handle cases where the input is empty.

In [2]:
def Frequency_Counter(data):
    result = {key: data.split(" ").count(key) for key in data.split(" ") }
    for x, i in enumerate(sorted(result.items())):
        print(x, str(i))

data = str(input("Give you paragraph to parse: "))
Frequency_Counter(data)

Give you paragraph to parse:  With these adjustments, the LaTeX document should compile without errors and include the table as intended.


0 ('LaTeX', 1)
1 ('With', 1)
2 ('adjustments,', 1)
3 ('and', 1)
4 ('as', 1)
5 ('compile', 1)
6 ('document', 1)
7 ('errors', 1)
8 ('include', 1)
9 ('intended.', 1)
10 ('should', 1)
11 ('table', 1)
12 ('the', 2)
13 ('these', 1)
14 ('without', 1)


# Task 04: Magic Square Validator

## Objective
Create a program that checks if a given 3x3 matrix forms a magic square.

## Requirements

1. A magic square is a square matrix where the sums of the numbers in each row, column, and both main diagonals are the same.
2. Ask the user to input a 3x3 matrix (nine integer values).
3. Check and print whether the given matrix forms a magic square.
4. Handle cases where the input matrix is not of size 3x3 or contains non-integer values.

In [2]:
import numpy as np

def Magic_checker(matrix):
    
    print(matrix)
    
    n = len(matrix)
    sum1 = 0
    sum2 = 0

    for i in range(n):
        sum1+=matrix[i][i]
        sum2+=matrix[i][n-i-1]
        
    if not (sum1==sum2):
        return False
        
    for i in range(n):
        sumr=0
        sumc=0
        
        for x in range(n):
            sumr+=matrix[i][x]
            sumc+=matrix[x][i]
        if not(sumr==sumc==sum1):
            return False
            
    return True

matrix = np.random.randint(1,9, size=(3,3))

if (Magic_checker(matrix)):
    print("Magic square")
else:
    print("Not Magic square")


[[6 6 5]
 [3 6 6]
 [1 5 1]]
Not Magic square


# Task 05: Palindromic Anagram Checker

## Objective
Create a program that checks if a given string can be rearranged to form a palindromic string.

## Requirements

1. A palindrome is a word, phrase, number, or other sequences of characters that reads the same forward and backward.
2. Ask the user to input a string.
3. Check and print whether the given string can be rearranged to form a palindrome.
4. Ignore spaces and consider the characters in a case-insensitive manner.
5. Handle cases where the input is empty or contains non-alphabetic characters.

In [6]:
def Palindrome_Check(data):
    NO_OF_CHARS = 256
    
    count = [0 for i in range (NO_OF_CHARS)]

    for i in data:
        count[ord(i)] +=1

    odd = 0
    for i in range(NO_OF_CHARS):
        if (count[i] & 1):
            odd += 1

        if (odd > 1):
            return False
    return True

data = str(input("Give any word: "))

Palindrome_Check(data)

if data:
    print("Palindrome")
else:
    print("Not Palindrome")
        

Give any word:  completed


Palindrome



<hr>
<h2>Congratulations, you have completed your hands-on lab in Python Conditions and Branching.
<hr>
