<h1><strong>Pandas</strong></h1>

In [1]:
import pandas as pd

In [3]:
import numpy as np
a = np.array([1])
b = np.array([1,4,5])
a+b

array([2, 5, 6])

<h2>Creating Series</h2>

In [4]:
data = np.random.randint(50, size=(10))
data

array([ 3, 22, 47, 20, 10, 41, 49, 11, 19, 26])

In [5]:
new_data = pd.Series(data)
new_data

0     3
1    22
2    47
3    20
4    10
5    41
6    49
7    11
8    19
9    26
dtype: int64

In [6]:
type(new_data)

pandas.core.series.Series

In [7]:
data_dict = {"a":2, "b":3, "c":4}
data_dict

{'a': 2, 'b': 3, 'c': 4}

In [8]:
dat=pd.Series(data_dict)
dat

a    2
b    3
c    4
dtype: int64

In [10]:
type(dat)

pandas.core.series.Series

In [11]:
new_arr = np.array(data)
new_arr

array([ 3, 22, 47, 20, 10, 41, 49, 11, 19, 26])

In [12]:
df = pd.Series(new_arr)
df

0     3
1    22
2    47
3    20
4    10
5    41
6    49
7    11
8    19
9    26
dtype: int64

In [14]:
df.shape

(10,)

In [25]:
data = np.random.randint(50, size=(10,4))
data

array([[42, 31, 10, 49],
       [27, 36, 15, 10],
       [26, 11,  5,  3],
       [20, 41, 28, 26],
       [21, 18, 47, 11],
       [19, 41, 49, 14],
       [11, 13, 21,  3],
       [43,  8,  6, 10],
       [ 3, 21, 13, 21],
       [34, 15, 16, 14]])

In [18]:
df = pd.DataFrame(data)
df

0   1   2  3
0  43  47   2  7
1   1  43  31  2

In [20]:
print(data[1][-1])

2


In [26]:
df = pd.DataFrame(data, columns=['Col1', 'Col2', 'Col3', 'Col4'])
df

Col1  Col2  Col3  Col4
0    42    31    10    49
1    27    36    15    10
2    26    11     5     3
3    20    41    28    26
4    21    18    47    11
5    19    41    49    14
6    11    13    21     3
7    43     8     6    10
8     3    21    13    21
9    34    15    16    14

In [27]:
new_dict={'Col1':np.random.randint(50, size=(4)), 'COl2':np.random.randint(50, size=(4))}
new_dict

{'Col1': array([ 3, 31, 49,  5]), 'COl2': array([45,  4, 13, 43])}

In [28]:
df = pd.DataFrame(new_dict)
df

Col1  COl2
0     3    45
1    31     4
2    49    13
3     5    43

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
d1= new_dict
d2= {"a":np.random.randint(50, size=(4)), "b":np.random.randint(50, size=(4))}
lod = [d1, d2]
lod

[{'Col1': array([ 3, 31, 49,  5]), 'COl2': array([45,  4, 13, 43])},
 {'a': array([21, 47, 49, 31]), 'b': array([39,  9, 47, 14])}]

In [31]:
df = pd.DataFrame(lod)
df

Col1             COl2                 a                b
0  [3, 31, 49, 5]  [45, 4, 13, 43]               NaN              NaN
1             NaN              NaN  [21, 47, 49, 31]  [39, 9, 47, 14]

In [32]:
df = pd.read_csv("car_details.csv")
df.head(10)

name  year  selling_price  km_driven    fuel  \
0              Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2       Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3     Datsun RediGO T Option  2017         250000      46000  Petrol   
4      Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5       Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6  Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7   Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8   Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9   Maruti Celerio Green VXI  2017         365000      78000     CNG   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
5  Individual       Manual   First Owner  
6  Individual       Manual   First Owner  
7  Individual       Manual  Second Owner  
8  Individual       Manual   First Owner  
9  Individual       Manual   First Owner

In [34]:
df.to_excel("DataFrame.xlsx")